### ISSUE TITLE
radvd to 2.19

### ISSUE THREAD

**Issue by Neustradamus** [freebsd/freebsd-ports-haskell#27]
Can you update radvd?
- https://github.com/freebsd/freebsd-ports-haskell/blob/master/net/radvd

Already here:
- https://github.com/freebsd/freebsd-ports/blob/master/net/radvd/

**Comment by arrowd** [comment]
This repository is not intended to be used by end users, but for collaboration on updating Haskell ports. Just use https://github.com/freebsd/freebsd-ports/ repository for the latest ports.
