### ISSUE TITLE
devel/hs-git-annex: Fails with GHC 9.2.2

### ISSUE THREAD

**Issue by arrowd** [freebsd/freebsd-ports-haskell#55]
Blocked by `bloomfilter`: https://github.com/bos/bloomfilter/pull/20

**Comment by blackgnezdo** [comment]
If you care to hack around the problem, the collection of necessary patches is in 
https://github.com/openbsd/ports/tree/master/devel/git-annex/patches

**Comment by arrowd** [comment]
Oh, thanks! I'll borrow that from your ports tree.
